exports.defaultOption = {
  paymentMethod: [
    {
      name: 'Vodafone cash',
      photo: '/images/v-cash.jpg',
      message: 'vodafone cash number 01020198197',
      needTimeReview: true,
      timeForReview: '2 hours',
      active: true,
    },
    {
      name: 'Binance pay',
      photo: '/images/binance.jpg',
      message: 'Binance pay id 0123456789',
      needTimeReview: true,
      timeForReview: '2 hours',
      active: false,
    },
    {
      name: 'PayPal',
      photo: '/images/paypal (1).png',
      message: 'PayPal account podapoda_poda@yahoo.com ',
      needTimeReview: true,
      timeForReview: '2 hours',
      active: true,
    },
  ],
  colors: {
    light: {
      brand50: '#eef2ff',
      brand100: '#e0e7ff',
      brand200: '#c7d2fe',
      brand500: '#6366f1',
      brand600: '#4f46e5',
      brand700: '#4338ca',
      brand800: '#3730a3',
      brand900: '#312e81',
      grey0: '#fff',
      grey50: '#f9fafb',
      grey100: '#f3f4f6',
      grey200: '#e5e7eb',
      grey300: '#d1d5db',
      grey400: '#9ca3af',
      grey500: '#6b7280',
      grey600: '#4b5563',
      grey700: '#374151',
      grey800: '#1f2937',
      grey900: '#111827',
      blue100: '#e0f2fe',
      blue700: '#0369a1',
      green100: '#dcfce7',
      green700: '#15803d',
      yellow100: '#fef9c3',
      yellow700: '#a16207',
      silver100: '#e5e7eb',
      silver700: '#374151',
      indigo100: '#e0e7ff',
      indigo700: '#4338ca',
      red100: '#fee2e2',
      red700: '#b91c1c',
      red800: '#991b1b',
    },
    dark: {
      brand50: '#eef2ff',
      brand100: '#e0e7ff',
      brand200: '#c7d2fe',
      brand500: '#6366f1',
      brand600: '#4f46e5',
      brand700: '#4338ca',
      brand800: '#3730a3',
      brand900: '#312e81',
      grey0: '#18212f',
      grey50: '#111827',
      grey100: '#1f2937',
      grey200: '#374151',
      grey300: '#4b5563',
      grey400: '#6b7280',
      grey500: '#9ca3af',
      grey600: '#d1d5db',
      grey700: '#e5e7eb',
      grey800: '#f3f4f6',
      grey900: '#f9fafb',
      blue100: '#075985',
      blue700: '#e0f2fe',
      green100: '#166534',
      green700: '#dcfce7',
      yellow100: '#854d0e',
      yellow700: '#fef9c3',
      silver100: '#374151',
      silver700: '#f3f4f6',
      indigo100: '#3730a3',
      indigo700: '#e0e7ff',
      red100: '#fee2e2',
      red700: '#b91c1c',
      red800: '#991b1b',
    },
  },
  footerBody: { email: 'podapoda_poda@yahoo.com', phone: '+20 102 0198 197' },
  logo: 'https://mmf6dud764kfnihq.public.blob.vercel-storage.com/public/img/items/logo-0.5080131496954754-1726929075403-ZhPT5q3L1f0Ymfe0ygGp5zlNoYDV2k.png',
  aboutUs: {
    p: `Welcome to our company! We are dedicated to providing the best services
        to our customers, ensuring satisfaction and excellence in every project
        we undertake.`,
    pp: `Our team is composed of highly skilled professionals who are passionate
        about their work. We believe in continuous improvement and innovation to
        stay ahead in the industry.`,
    ppp: ` Thank you for choosing us. We look forward to collaborating with you and
        achieving great success together. Let's make something amazing!`,
  },
  numItems: {
    numItemsInHomePage: 10,
    numItemsInCategoryPage: 10,
    numItemsInManageItemsPage: 5,
    numItemsInManageReviewsPage: 5,
    numItemsInWishListPage: 10,
    numReviewInPage: 6,
    numOrderInManageOrdersPage: 5,
    numUsersInManageUsersPage: 6,
  },
  offersLine: [
    'Limited Time Offer: Grab Your Favorites Now!',
    'Exclusive Deals Just for You: Shop and Save!',
    'Hurry! Special Discounts Ending Soon!',
  ],
  initialSEOData: {
    homeTitle: 'Welcome to Our Home Page',
    homeDescription: 'Discover the best products and services on our home page.',
    homeKeywords: 'home, products, services',
    aboutTitle: 'About Us',
    aboutDescription: 'Learn more about our company and our mission.',
    aboutKeywords: 'about, company, mission',
    customerServiceTitle: 'Customer Service',
    customerServiceDescription: 'Get help and support from our customer service team.',
    customerServiceKeywords: 'customer service, support, help',
    orderActiveTitle: 'Active Orders',
    orderActiveDescription: 'View and manage your active orders.',
    orderActiveKeywords: 'active orders, manage orders',
    orderHistoryTitle: 'Order History',
    orderHistoryDescription: 'Check your past orders and purchase history.',
    orderHistoryKeywords: 'order history, past orders',
    personalInfoTitle: 'Personal Information',
    personalInfoDescription: 'Update your personal information and preferences.',
    personalInfoKeywords: 'personal information, preferences',
    cartTitle: 'Shopping Cart',
    cartDescription: 'Review the items in your shopping cart.',
    cartKeywords: 'shopping cart, items',
    checkoutTitle: 'Checkout',
    checkoutDescription: 'Complete your purchase and checkout.',
    checkoutKeywords: 'checkout, purchase',
    wishlistTitle: 'Wishlist',
    wishlistDescription: 'Save items to your wishlist for later.',
    wishlistKeywords: 'wishlist, save items',
    loginTitle: 'Login',
    loginDescription: 'Access your account by logging in.',
    loginKeywords: 'login, access account',
    signupTitle: 'Sign Up',
    signupDescription: 'Create a new account to start using our services.',
    signupKeywords: 'sign up, create account, register',
    forgetPasswordTitle: 'Forgot Password',
    forgetPasswordDescription: 'Recover your account by resetting your password.',
    forgetPasswordKeywords: 'forgot password, reset password, recover account',
  },
  headerStyle: 'String',
  footerStyle: 'String',
  dashboardStyle: 'String',
};
