const mongoose = require('mongoose');

const colorSchema = new mongoose.Schema({
  light: {
    brand50: String,
    brand100: String,
    brand200: String,
    brand500: String,
    brand600: String,
    brand700: String,
    brand800: String,
    brand900: String,
    grey0: String,
    grey50: String,
    grey100: String,
    grey200: String,
    grey300: String,
    grey400: String,
    grey500: String,
    grey600: String,
    grey700: String,
    grey800: String,
    grey900: String,
    blue100: String,
    blue700: String,
    green100: String,
    green700: String,
    yellow100: String,
    yellow700: String,
    silver100: String,
    silver700: String,
    indigo100: String,
    indigo700: String,
    red100: String,
    red700: String,
    red800: String,
  },
  dark: {
    brand50: String,
    brand100: String,
    brand200: String,
    brand500: String,
    brand600: String,
    brand700: String,
    brand800: String,
    brand900: String,
    grey0: String,
    grey50: String,
    grey100: String,
    grey200: String,
    grey300: String,
    grey400: String,
    grey500: String,
    grey600: String,
    grey700: String,
    grey800: String,
    grey900: String,
    blue100: String,
    blue700: String,
    green100: String,
    green700: String,
    yellow100: String,
    yellow700: String,
    silver100: String,
    silver700: String,
    indigo100: String,
    indigo700: String,
    red100: String,
    red700: String,
    red800: String,
  },
});

const paymentMethodSchema = new mongoose.Schema({
  name: { type: String, required: true },
  photo: { type: String, required: true },
  message: { type: String, required: true },
  needTimeReview: { type: Boolean, required: true, default: true },
  timeForReview: { type: String, required: true },
  active: { type: Boolean, required: true, default: true },
});

const optionSchema = new mongoose.Schema({
  paymentMethod: { type: [paymentMethodSchema], required: true },
  cashOnDelivery: { type: Boolean, default: true },
  logo: String,
  category: [{ name: String, photo: String }],
  offers: [String],
  colors: colorSchema,
  footerBody: { email: String, phone: String },
  headerStyle: String,
  footerStyle: String,
  dashboardStyle: String,
});

const Option = mongoose.model('Option', optionSchema);

module.exports = Option;
